name: Ayodo add-on
version: "0.0.6"
slug: hayodo
description: Ayodo tunnel
url: "https://ayodo.ru"

startup: services
boot: auto
host_network: true
init: false

arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
map:
  - addon_config:rw
  - ssl:rw
  - share:rw

options:
  token: ""
  lets_encrypt:
    accept_terms: false
    algo: secp384r1
    certfile: fullchain.pem
    keyfile: privkey.pem
    renew_days: 30
  local_host: "homeassistant"
  local_port: 8123
  email: ""
schema:
  token: str
  accept_terms: bool
  email: str
  lets_encrypt:
    algo: list(rsa|prime256v1|secp384r1)
    certfile: str
    keyfile: str
    renew_days: int
  local_host: str
  local_port: int

ingress: true
panel_icon: mdi:certificate
panel_title: "Certificates"
panel_admin: true
